bid/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('bidproj.urls', namespace='bid'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

bidproj/urls.py
from django.urls import path
from . import views
app_name = 'bidproj'
from django.contrib.auth import views as auth_view
urlpatterns = [
    path('login/', auth_view.LoginView.as_view(), name='login'),
    path('', views.index, name='index'),
    path('logout/', auth_view.LogoutView.as_view(), name='logout'),
    path('register', views.register, name='register'),
    path('passwordchange/', auth_view.PasswordChangeView.as_view(), name='password_change'),
    path('passwordchangedone/', auth_view.PasswordChangeDoneView.as_view(), name='password_change_done'),
    
]

bidproj/models.py
from django.db import models

from django.conf import settings
from django.db.models.expressions import OrderBy

# Create your models here.

class BidProduct(models.Model):
    CHOICES = [('fashion', 'fashion'), ('vehicles', 'vehicles'), ('others', 'others')]
    product_name = models.CharField(max_length=100)
    description = models.TextField()
    category = models.CharField(max_length=100, choices=CHOICES)
    period_on_bid = models.DateTimeField(blank=True, null=True)
    upload_time = models.DateTimeField(auto_now_add=True, db_index=True)
    
    uploaded_by = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    uploaded_price = models.DecimalField(decimal_places=2, max_digits=10) 
    
    product_image = models.ImageField(upload_to='biduploads')
    current_bid = models.DecimalField(decimal_places=2, max_digits=10)
    
    class Meta:
        ordering = ['-upload_time']
        
    def __str__(self):
        return self.product_name

bidproj/forms.py
from django import forms
from django.core.exceptions import ValidationError
from django.contrib.auth.models import User


class Registration(forms.ModelForm):
    
    password1 = forms.CharField(label='password', widget=forms.PasswordInput)
    password2 = forms.CharField(label='Retype Password', widget=forms.PasswordInput)
    class Meta:
        model = User
        fields = ['username', 'first_name', 'email']
    def validate_password(self):
        password1 = self.cleaned_data['password1']
        password2 = self.cleaned_data['password2']
        
        if password1 != password2:
            raise forms.ValidationError('passwords do not match')
        elif len(password1) < 6:
            raise forms.ValidationError('Password must be at least six characters long')
        
        
        return self.cleaned_data['password1']

bidproj/views.py
from django.http.response import JsonResponse
from django.shortcuts import render
from django.http import HttpResponse, HttpResponseRedirect, JsonResponse
from .forms import Registration
from .models import BidProduct
# Create your views here.
from django.contrib.auth.models import User


def index(request):
    uploads = BidProduct.objects.all().order_by('-upload_time')[:10]
    recentUploads = []
    
    for item in uploads:
        bid = {
            'product_name' : item.product_name,
            'uploaded_by': item.uploaded_by.username,
            'current_bid': float(item.current_bid),
            'product_image': item.product_image.url,
            'description': item.description
        }
        recentUploads.append(bid)
    if request.method == 'POST':
        
        search = request.POST['search']
        bidsQuery = BidProduct.objects.filter(product_name__icontains=search).order_by('-upload_time').all()[:20]
        categoryQuery = BidProduct.objects.filter(category__icontains=search).order_by('-upload_time').all()[:20]
        bids = list(categoryQuery)
        for item in bidsQuery:
            if not item in categoryQuery:
                bids.append(item)
        
        bidnames = [{"bid_name":bid.product_name,"uploaded_by": bid.uploaded_by.username} for bid in bids]
                    
        return JsonResponse({'bids': str(bidnames)})
    return render(request, 'bidproj/index.html', {'recentUploads': recentUploads})

def register(request):
    form = Registration()
    if request.method == 'POST':
        form = Registration(request.POST)
        if form.is_valid():
            
            username = form.cleaned_data['username']
            password = form.cleaned_data['password1']
            email = form.cleaned_data['email']
            first_name = form.cleaned_data['first_name']
            User.objects.create_user(username, email, password)
            user = User.objects.get(username=username)
            user.first_name = first_name
            user.save()
            
            return render(request, 'registration/registration_done.html', {'form': form})
            
    return render(request, 'registration/register.html',{'form': form})

bidproj/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, shrink-to-fit=no">
    <title>Bid your way</title>
    <style>
        *{
            margin: 0px;
            padding: 0px;
            font-family: 'Trebuchet MS', 'Lucida Sans Unicode', 'Lucida Grande', 'Lucida Sans', Arial, sans-serif;
        }
        .div{
                
                display: flex;
                flex-wrap: wrap;
                justify-content: center;
                padding: 12px;
                box-shadow:1px 2px 10px 0px rgb(162, 160, 160);
                margin-bottom: 15px;
                font-size: 30px;
                font-weight: bolder;
                color: rgb(92, 92, 92);
            }
            .form{ 
             padding: 15px;
             margin: 10px;
             border-radius: 5px;
             box-shadow: 1px 2px 10px 0px rgb(162, 160, 160);
            }
            .form:hover{
                background-color: rgb(252, 252, 252);
            }
            
            
            form > p{
                margin-bottom: 10px;
            }
            @media screen and (max-width: 900px){
               .form input{
                width: 80%;
               } 
            }
            @media screen and (min-width: 900px){
                .form{ 
                    width: 50%;
            }
            .form input{
                width: 80%;
               } 
            }
            .form input, .form select{
                font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Oxygen, Ubuntu, Cantarell, 'Open Sans', 'Helvetica Neue', sans-serif;
                height: 30px;
                border: 1px solid rgb(209, 208, 208);
                border-radius: 7px;
                padding: 5px;
            }
            input:hover, select:hover{
                background-color: rgb(247, 245, 245);
            }
            .form button{
                background-color: lightseagreen;
                padding: 10px;
                color: white;
                border: 1px solid lightseagreen;
                border-radius: 3px;
                box-shadow: 1px 2px 3px 2px lightseagreen;
                cursor: pointer;
            }
            
    </style>
</head>
<body>
    
    {% block body %}
    {% endblock %}
</body>
</html>

bidproj/templates/bidproj/index.html
{% extends 'base.html' %}
{% block body %}
    <div id='top'>
        <script>
            document.addEventListener('DOMContentLoaded', () => {
                var button = document.querySelector('#search')
               

                let search = document.querySelector('#searchbids')
                //search.onkeyup = () => {
                button.onclick = () => {
                    if(search.value.length >= 1){
                    button.disabled = false
                    
                    request = new XMLHttpRequest()
                    var form = new FormData()
                    form.append('csrfmiddlewaretoken', '{{ csrf_token}}')
                    form.append('search', search.value)

                    request.open('POST', '{% url "bidproj:index" %}')
                    request.onload = () => {
                        res = JSON.parse(request.responseText)
                        //alert(JSON.stringify(res))
                        let searchResults = document.querySelector('#searchResults')
                       
                        searchResults.classList.add('searchResults')
                        if(eval(res.bids).length > 0){
                            searchResults.innerHTML = '<h3>Search Results</h3><br>'
                            for(item of eval(res.bids)){
                                let result = document.createElement('div')
                                result.classList.add('searchResult')
                                // Add anchor here
                                result.innerHTML = `${item.bid_name} uploaded by ${item.uploaded_by}`
                                searchResults.appendChild(result)
                            }
                            }
                            else{
                                searchResults.innerHTML = "<h3>Ooops, we couldn't find your search</h3><br>"
                            }
                        
                    }
                    
                    request.send(form)
                }
                    else{
                        return false
                        button.disabled = true
                    }
                }


            })
        </script>
        <style>
            .searchResults{
                box-shadow: 1px 1px 8px 1px grey;
                padding: 25px;
                text-align: center;
                margin: auto;
                border-radius: 25px;
                margin-top: 10px;
            }

            .searchResults div{
                margin-bottom: 12px;
                margin-top: 12px;
                padding: 10px;
                border-bottom: 1px solid rgb(240, 239, 239);

            }


            #top{
                display: flex;
                flex-wrap: wrap;
                background-color: rgb(1, 1, 38);
                color: rgb(241, 241, 247);
                padding: 10px;
            }
            #top > h2{
                width: 100%;
            }
            #top #indexSearches{
                margin: auto;
                /* display: flex;
                flex-wrap: wrap; */

            }
            #indexSearches input{
                height: 34px;
                border-bottom-left-radius: 10px;
                border-top-left-radius: 10px;
                margin-right: 0px;
                font-size: large;
            }

            #indexSearches button{
                width: 60px;
                height: 36px;
                color: white;
                
                border-bottom-right-radius: 10px;
                border-top-right-radius: 10px;
                margin-left:0px;
                background-color: lightseagreen;
            }
            
            @media screen and (max-width: 800px){
            #indexSearches input{
                width: 75%;
            }
            

            }
            @media screen and (min-width: 801px){
                .searchResults{
                    width: 50%;
                }
                #indexSearches input{
                width: 50%;}
        
            }

        </style>
        {% if request.user %}
            <h2>Welcome {{request.user.username}}</h2>
        {% endif %}

        <div id='indexSearches'>
            <h2>What do you want to to buy today</h2>
            <div>
                <input type='text' name='searchbids' id='searchbids'>
                <button id='search'>Search</button>
            </div>
        </div>
    </div>
    <div id='searchResults'></div>

    <div id='recentUploads'>
        <style>
            #recentUploads{
                display: flex;
                flex-wrap: wrap;
                justify-content: center;
                width: 100%;
            }

            #recentUploads > h2{
                width: 100%;
                text-align: center;
                padding: 15px;
                box-shadow: 0px 0px 3px 0px grey;
            }
            #recentUploads #uploads{
                padding: 10px;
            }
            
            
            .recentBids{
               display: flex; 
               flex-wrap: wrap;
               box-shadow: 0px 1px 8px 1px grey;
               cursor: pointer;

            }
            .recentBids:hover{
                background-color:rgb(250, 250, 250);
            }
            #aboutProduct p{
                font-size: x-large;
                padding-bottom: 15px;
                padding-left: 10px;
                
            }
            #uploads{
                display: flex;
                flex-wrap: wrap;
                justify-content: space-around;
            }
            @media screen and (max-width: 800px){
                .recentBids{
                    width: 80%;
                    margin: auto;
                    margin-bottom: 20px;;
                }
                .productImg{
                    width: 100%;

                }
                .productImg img{
                    width: 100%;
                }
                #aboutProduct p{
                    font-size: x-large;
                    display: flex;
                    flex-wrap: wrap;
                    width: 100%;
                
            }
            }
            @media screen and (min-width: 800px){
                .productImg{
                    width: 40%;  
                }
                .productImg img{
                    width: 100%;
                }

                .recentBids{
                    width: 45%;
                    border-bottom-right-radius: 20px;
                    border-top-right-radius: 20px;
                    
                }
            

            }
            #aboutProduct{
                padding-bottom: 15px; 
            }

            #aboutProduct p{
                
                display: flex;
                flex-wrap: wrap;
            }

            #aboutProduct span{
                background-color: rgb(79, 125, 154);
                
                padding: 14px;
                 color: white;
            }
            .hide{
                display: none;
            }
        </style>
        <script>
            document.addEventListener('DOMContentLoaded', () => {
                recentBids = document.querySelectorAll('.recentBids')  
                recentBids.forEach(function(bid){
                    bid.onmouseover = function(){
                        this.querySelector('span').classList.add('hide')
                        this.querySelector('.displayOnHover').style.display = 'flex'
                        this.querySelector('.displayOnHover').style.flexWrap = 'wrap'
                    }
                    bid.onmouseout = function(){
                        this.querySelector('span').classList.remove('hide')
                        this.querySelector('.displayOnHover').style.display = 'none'
                    }
                })
            })
        </script>
        <h2>RECENTLY UPLOADED BIDS</h2>
        <div id='uploads'>
            {% if recentUploads %}
                {% for bid in recentUploads %}
                    <div class='recentBids'>
                        <div class='productImg'>
                            <img src='{{ bid.product_image }}'>
                        </div>

                        <div id='aboutProduct'>
                            <p>{{ bid.product_name}}</p>
                            <p>Uploaded By: {{ bid.uploaded_by }}</p>
                            <p>Current Bid: {{ bid.current_bid }}</p>
                            <span><strong>Learn more</strong></span>
                            <p class='displayOnHover' style='display: none;'>Product Description: {{ bid.description }}</p>
                        </div>

                    </div>
                {% endfor %}
            {% endif %}
        </div>
    </div>
{% endblock %}